SCR_MissionHeader {
 World "{ABB7A5211695880E}Worlds/7Cav_SB_Arland.ent"
 m_sName "7Cav Sandbox Arland"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
 m_ACE_Settings ACE_MissionHeaderSettings "{69FA2DC65842E0CB}" {
  m_ACE_Captives_Settings ACE_Captives_Settings "{69FA2DC79FF06851}" {
   m_eTakeAICaptiveRequirements FROM_BEHIND_FOR_ARMED
  }
  m_ACE_Medical_Defibrillation ACE_Medical_Defibrillation_Settings "{69FA2DC65487D730}" {
   m_eDefibSettingPreset Arcade
  }
 }
}